### DISCUSSION TITLE
如何在有多个vlan interface的机器上明确指定interface做NAT

### DISCUSSION THREAD

**Discussion by huangmingyou** [EHfive/einat-ebpf#27] [Q&A] [answered]
比如有vlan 2 3 4 5 四个interface ,只需要对 从 vlan 2 进，从vlan 4 出去的流量做NAT,如何设置呢，我阅读了一下config.toml文件，没看太明白。是需要每张网卡属性里面设置 nat44=true和 nat44=false来开关，以及通过限制网段和设置no_snat属性来控制。

**Comment by EHfive** [comment, marked as answer]
The vlan does not matter here, it's the "visibility" (external and internal) of interfaces and IP addresses assigned matter.

```toml
[[interfaces]]
# your external interface
if_name = "external"
nat44 = true
ipv4_hairpin_route.internal_if_names = ["lo", "internal"]
# internal network that your internal interface belongs to
snat_internals = [ "192.168.1.0/24" ]
```

Note that `snat_internals` is useful only if you have external route-able address assigned to your internal devices, use nftables/iptables instead for firewall purpose. See also https://github.com/EHfive/einat-ebpf/issues/21.
